export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = "CREATE_INVOICE_SUCCESS";
export const CREATE_INVOICE_FAIL = "CREATE_INVOICE_FAIL";
export const CREATE_INVOICE_RESET = "CREATE_INVOICE_RESET";

export const GET_ALLINVOICE_REQUEST = "GET_ALLINVOICE_REQUEST";
export const GET_ALLINVOICE_SUCCESS = "GET_ALLINVOICE_SUCCESS";
export const GET_ALLINVOICE_FAIL = "GET_ALLINVOICE_FAIL";

export const GET_LOGGED_IN_INVOICE_REQUEST = "GET_LOGGED_IN_INVOICE_REQUEST";
export const GET_LOGGED_IN_INVOICE_SUCCESS = "GET_LOGGED_IN_INVOICE_SUCCESS";
export const GET_LOGGED_IN_INVOICE_FAIL = "GET_LOGGED_IN_INVOICE_FAIL";

export const GET_SINGLE_INVOICE_REQUEST = "GET_SINGLE_INVOICE_REQUEST";
export const GET_SINGLE_INVOICE_SUCCESS = "GET_SINGLE_INVOICE_SUCCESS";
export const GET_SINGLE_INVOICE_FAIL = "GET_SINGLE_INVOICE_FAIL";

export const INVOICE_DELETE_REQUEST = "INVOICE_DELETE_REQUEST";
export const INVOICE_DELETE_SUCCESS = "INVOICE_DELETE_SUCCESS";
export const INVOICE_DELETE_FAIL = "INVOICE_DELETE_FAIL";
export const INVOICE_DELETE_RESET = "INVOICE_DELETE_RESET";

export const INVOICE_UPDATE_REQUEST = "INVOICE_UPDATE_REQUEST";
export const INVOICE_UPDATE_SUCCESS = "INVOICE_UPDATE_SUCCESS";
export const INVOICE_UPDATE_FAIL = "INVOICE_UPDATE_FAIL";
export const INVOICE_UPDATE_RESET = "INVOICE_UPDATE_RESET";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";
export const UPDATE_STATUS_RESET = "UPDATE_STATUS_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";